### ISSUE TITLE
Unable to view trace results in AWS X ray

### ISSUE THREAD

**Issue by wtfoong** [patrickkerrigan/php-xray#13]
hello, i am currently working on a php website and would like to use AWS x-ray to for insights, but after implementing and following the guide i am still unable to get any data from AWS x ray.

The code i use for testing is from one of the previous issues and was working in that issue.
![image](https://user-images.githubusercontent.com/66662848/205895122-ef36f7ef-5fa7-460b-bf5a-fcc7e52853a0.png)

and the result at AWS x ray 
![image](https://user-images.githubusercontent.com/66662848/205895209-2b73c121-131f-4420-97c8-a0506ed99ca4.png)

would appreciate your help very much....tqvm....XD

**Comment by patrickkerrigan** [comment]
Hi,

Looking at the code you've got so far I think I can see a couple of issues that might be preventing the traces showing up properly in x-ray.

Firstly, I'd recommend using the example in one of the later comments in the issue I think you're referring to: https://github.com/patrickkerrigan/php-xray/issues/11#issuecomment-953736831. This should have everything that's needed for x-ray to reliably link the two requests together. If the API you're calling doesn't have its own tracing, then you should remove `->setTraced(true)` otherwise x-ray will wait for the API to submit its own trace before showing in the dashboard.  That being said, the example you used should result in _something_ being recorded, so I suspect something else must be off.

The next thing I noticed is that `$xrayHeader` is undefined in the code you posted, whereas in the issue comment it's set correctly to `"X-Amzn-Trace-Id"`.

Finally, and this may be a stupid question, but do you have the [AWS x-ray daemon](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon.html) installed and running? By default this library will expect to find the daemon listening on `127.0.0.1:2000`, but if you're running it on a remote host or another port then you can pass a hostname/IP address and port to the constructor of `DaemonSegmentSubmitter`.

If you still have trouble after the above is sorted, then it might be worth testing with the most simple case first to verify that communication with the x-ray daemon and onwards to AWS is working correctly before moving onto cross-service tracing. Something such as this should be the minimum you need to produce a trace and test that out:

```php
use Pkerrigan\Xray\Trace;
use Pkerrigan\Xray\Submission\DaemonSegmentSubmitter;

Trace::getInstance()
    ->setTraceHeader($_SERVER['HTTP_X_AMZN_TRACE_ID'] ?? null)
    ->setName('app.example.com')
    ->setUrl($_SERVER['REQUEST_URI'])
    ->setMethod($_SERVER['REQUEST_METHOD'])
    ->begin(); 

sleep(1); // give x-ray something to actually measure

Trace::getInstance()
    ->end()
    ->setResponseCode(http_response_code())
    ->submit(new DaemonSegmentSubmitter());
```

Hopefully that helps, but if you don't have any luck then let me know and I'll see if I can put together some further troubleshooting steps.

**Comment by wtfoong** [comment]
Thank you for your reply,
After implementing your simple case i manage to get a different response from x ray daemon, but it says that i have no credentials provider eventhough i am on a EC2 instance
![image](https://user-images.githubusercontent.com/66662848/206334346-8fded1d8-01ad-4330-9709-f7e44ede6482.png)
could it be because i am using a learner account?

this is the code that i am currently using.
```
<?php
require(__DIR__ . '/vendor/autoload.php');
use Pkerrigan\Xray\Trace;
use Pkerrigan\Xray\Submission\DaemonSegmentSubmitter;

Trace::getInstance()
    ->setTraceHeader($_SERVER['HTTP_X_AMZN_TRACE_ID'] ?? null)
    ->setName('app.example.com')
    ->setUrl($_SERVER['REQUEST_URI'])
    ->setMethod($_SERVER['REQUEST_METHOD'])
    ->begin(); 

sleep(1); // give x-ray something to actually measure

Trace::getInstance()
    ->end()
    ->setResponseCode(http_response_code())
    ->submit(new DaemonSegmentSubmitter());
?>
<h1>test</h1>
```

**Comment by patrickkerrigan** [comment]
It looks from that log snippet like your code is submitting traces to the daemon now, so once the credentials issue is fixed you _should_ be good.

I'm not familiar with learner accounts and if there are any differences from a full account, but I would assume they should support enough of the functionality for this to work.

> from what i understand if it runs on EC2, it should be able to get the credentials automatically

This is correct, at least on a full account, but only if you've granted permission to your EC2 instance to access x-ray. You do this by creating and assigning an [IAM role](https://docs.aws.amazon.com/xray/latest/devguide/security_iam_service-with-iam.html#xray-permissions-aws) to your EC2 instance with the `AWSXRayDaemonWriteAccess` permission:

![image](https://user-images.githubusercontent.com/20188719/206581355-27b0f81e-02c7-4c60-907a-19b4b814bcc3.png)

If your instance has no IAM role, then it has no credentials to get, and you'd receive the error in your screenshot.

If you already have an IAM role assigned, then you'll need to modify it to include the `AWSXRayDaemonWriteAccess` permission.

You may need to restart the x-ray daemon after making any changes to the IAM role if it doesn't pick them up automatically.

**Comment by wtfoong** [comment]
I manage to brute force through it by adding a .aws folder with a credentials file in it to my root user.....pretty sure this is not the correct way, but i manage to get the xray to detect my traces.

![image](https://user-images.githubusercontent.com/66662848/206600918-62bed6e9-9cd0-4292-9521-f1496e494ef4.png)
i currently am able to trace my db call and webpage.

i would like to ask would it be possible to trace my AWS service calls? like the time needed to upload an image to S3, cause from what i see, all the traces focus on the web site response time.

tqvm

**Comment by wtfoong** [comment]
ok, tqvm for your help, really appreciate it...XD
